name: Run Tests

on:
  push:
    tags:
      - v*
    branches:
      - '**'
  pull_request:

jobs:
  test:
    name: Integration Test

    strategy:
      matrix:
        server:
          - 7.6.1
          - 7.2.4
          - 7.1.6
          - 7.0.5

    runs-on: ubuntu-20.04
    steps:
      - name: Install cbdinocluster
        run: |
          mkdir -p "$HOME/bin"
          wget -nv -O $HOME/bin/cbdinocluster https://github.com/couchbaselabs/cbdinocluster/releases/download/v0.0.41/cbdinocluster-linux-amd64
          chmod +x $HOME/bin/cbdinocluster
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Initialize cbdinocluster
        run: |
          cbdinocluster -v init --auto
      - name: Start couchbase cluster
        env:
          CLUSTERCONFIG: |
            nodes:
              - count: 3
                version: ${{ matrix.server }}
                services: [kv, n1ql, index, fts, cbas, eventing]
            docker:
              kv-memory: 512
        run: |
          CBDC_ID=$(cbdinocluster -v alloc --def="${CLUSTERCONFIG}")
          cbdinocluster -v buckets add ${CBDC_ID} default --ram-quota-mb=100 --flush-enabled=true --num-replicas=2
          cbdinocluster -v collections add ${CBDC_ID} default _default test
          CBDC_CONNSTR=$(cbdinocluster -v connstr $CBDC_ID)
          echo "CBDC_ID=$CBDC_ID" >> "$GITHUB_ENV"
          echo "CBDC_CONNSTR=$CBDC_CONNSTR" >> "$GITHUB_ENV"

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Initialize deps
        run: go get
      - name: Run tests
        timeout-minutes: 40
        run: go test ./... -v -race --connstr ${{ CBDC_CONNSTR }} --user Administrator --pass password --cluster-version ${{ matrix.server }}
