name: Run Build Targets

on:
  push:
    tags:
      - v*
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        target:
          - goos: linux
            goarch: amd64
            runs_on: ubuntu-latest
          - goos: linux
            goarch: arm64
            runs_on: ubuntu-latest
          - goos: windows
            goarch: arm64
            runs_on: windows-latest
          - goos: windows
            goarch: amd64
            runs_on: windows-latest
          - goos: darwin
            goarch: amd64
            runs_on: macos-latest
          - goos: darwin
            goarch: arm64
            runs_on: macos-latest

    runs-on: ${{ matrix.target.runs_on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Initialize deps
        run: go get
      - name: Run build
        run: go build
